# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35f57205ddec8180748663f52f3c41e8f775cdf94eae3eba28a8ae97cceca737fd49716812fb63f4d52c04551793809065836e75965e22e75efe2420b040964f

test:
  secret_key_base: 3fab893b1707879327ad0d74d31f57df83331421b91f70bd37c0acd3045acb8bec52b727fb5683d21430fccadf5f358bc2920574c5e9965043c139d8b0739c1c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
